version: '2.1'
services:   
    app:    
        restart: always    
        build: .    
        ports:      
            - 80:80  
        volumes:      
            - .:/app
        environment:
            - DEBUG=1
            - PYTHONPATH=/